-- MySQL Script generated by MySQL Workbench
-- Fri 03 Nov 2017 02:43:58 PM COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workshop-test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workshop-test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workshop-test` DEFAULT CHARACTER SET utf8 ;
USE `workshop-test` ;

-- -----------------------------------------------------
-- Table `workshop-test`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop-test`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
